---
dev_addr: "127.0.0.1:8001"
edit_uri: "edit/docs"
site_name: "jdiff Documentation"
site_url: "https://jdiff.readthedocs.io/"
site_dir: /docs
repo_url: "https://github.com/networktocode-llc/jdiff"
theme:
  name: "readthedocs"
  navigation_depth: 4
  hljs_languages:
    - "django"
    - "yaml"
extra_css:
  - "extra.css"
markdown_extensions:
  - "admonition"
  - toc:
      permalink: true
# plugins:
#   - include-markdown
nav:
  - Introduction: "index.md"
  - Usage: "usage.md"
  - Architecture: "architecture.md"
  - Examples: "example.md"
  - Development Environment: "development.md"